### ISSUE TITLE
In the new federal system, how many local bodies are there?

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/data#17]
The geo data used to create the geography table for https://github.com/Code4Nepal/nepalmap_federal has 774 local bodies.

The data in https://github.com/Code4Nepal/data/tree/master/Federal%20Data/753%20Local%20Unit%20Population%20and%20HouseHold suggests that there are 753 local bodies.

What is the right answer? There needs to be a match in order for the geographic data and the census data to work together correctly in nepalmap.

Here is a CSV file showing the localities that have been imported into the geography table for nepalmap_federal:
[localities.csv.zip](https://github.com/Code4Nepal/data/files/2334005/localities.csv.zip)

**Comment by ravinepal** [comment]
There are total of 761 admin bodies/govs in Nepal. 

- 1 national admin/boundary, 
- 7 provinces and 
- 753 local admin/boundaries

Does this help?

**Comment by cliftonmcintosh** [comment]
Thanks. The data that Nitesh got for geographic boundaries has 774 local
bodies. Maybe the difference between that and the 753 local governments is
that some of those are things like national parks?

**Comment by ravinepal** [comment]
That's likely the case. @nikeshbalami ?

**Comment by nikeshbalami** [comment]
Yes @cliftonmcintosh, Like @ravinepal said there are 753 local bodies in total, and remaining boundaries are of National Parks, Hunting reserves, conversation areas etc.
