### ISSUE TITLE
Clean up federal population data files

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/data#18]
Remove lines with no data
Remove extra spaces around headers (for example, turn "Total Population " into "Total Population")

**Comment by ravinepal** [comment]
hi @pratimakandel - may I request you to look into this over the weekend and submit a pull request so @cliftonmcintosh can review the updates?

**Comment by nikeshbalami** [comment]
Hi @pratimakandel, I just submitted the PR so you don't have to edit it.
