### ISSUE TITLE
Scrape data about agricultural production in Nepal 

### ISSUE THREAD

**Issue by ravinepal** [Code4Nepal/data#2]
Here's [the dataset](http://moad.gov.np/public/uploads/1142453195-STATISTIC%20AGRICULTURE%20BOOK_2016.pdf) published by the Government of Nepal. 

Here's a [detailed guide ](https://github.com/Code4Nepal/nepalmap_app/wiki/Collecting-and-visualizing-data-in-NepalMap) by @cliftonmcintosh on how we will use the data and how your data should look like when you submit here.

We'd like to scrape and visualize from the document:
Major Cereal Crops by Districts
Cash Crops by Districts
Oil Seed Crops by Districts
~~Jute by Districts~~ Done in https://github.com/Code4Nepal/data/pull/3
~~Cotton by Districts~~ Done in https://github.com/Code4Nepal/data/pull/3
~~Tea by Districts
Coffee by Districts
Pulses by Districts
Live Stock Population by Districts
Milk Animals and Milk Production by Districts
Net Meat Production by Districts
Egg Production by Districts
Wool Production by Districts
Yak/ Nak/ Chauri Population by Districts
Rabbit Population by Districts
Horse/Asses Population by Districts
Water Surface Area and production of fish by Districts~~ done in https://github.com/Code4Nepal/data/pull/5
Citrus Fruits: Area, Productive Area, Production, and Yield by Districts
Summer Fruits: Area, Productive Area, Production, and Yield by Districts
Fresh Vegetable Crops: Districtwise Area, Production and Yield

**Comment by cliftonmcintosh** [comment]
@ravinepal 

Can you provide some guidance on what a complete data set in CSV form would look like so that potential contributors will know how to shape their data?

**Comment by ravinepal** [comment]
Thanks, @cliftonmcintosh!  Just updated the issue with the guide you have created!

**Comment by cliftonmcintosh** [comment]
@ravinepal 

Excellent. Thank you!

**Comment by amitness** [comment]
@nikeshbalami Can you strike out the ones you've already added through #4 ?

**Comment by nikeshbalami** [comment]
I don't have edit access @amitness, List fo datasets which are complete.
Tea by Districts
Coffee by Districts
Pulses by Districts
Live Stock Population by Districts
Milk Animals and Milk Production by Districts
Net Meat Production by Districts
Egg Production by Districts
Wool Production by Districts
Yak/ Nak/ Chauri Population by Districts
Rabbit Population by Districts
Horse/Asses Population by Districts
Water Surface Area and production of fish by Districts

**Comment by amitness** [comment]
@nikeshbalami I've updated it. Thanks for the list.

**Comment by cliftonmcintosh** [comment]
@nikeshbalami 

Great work. I have some questions:

What is "chevon" in the meat production?
Is "mutton" goat in the meat production? (It was certainly my experience in Nepal that goat meat was common. I never saw sheep meat, but maybe things have changed!)

**Comment by nikeshbalami** [comment]
Yeah @cliftonmcintosh, in data Mutton = Goat meat and Chevon = Sheep meat.
