### ISSUE TITLE
Create data set on travel time to nearest government health facility

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/data#25]
For the upcoming [federal version of NepalMap](https://github.com/Code4Nepal/nepalmap_federal), we would like to present data on the travel time to nearest government health facility. These data are available in Table 2.6 on page 25 of the Nepal Demographic and Health Survey of 2016 ([PDF here](https://www.dhsprogram.com/pubs/pdf/FR336/FR336.pdf)). Extract the data from Table 2.6 so that it is in a csv that conforms to the following specifications:
- It should have three columns: province, travel time, total
- The columns should be separated by commas
- The headers should be the first row in the CSV
- The "travel time" options should be "LESS_THAN_THIRTY_MINUTES", "THIRTY_TO_SIXTY_MINUTES", "MORE_THAN_SIXTY_MINUTES", "UNKNOWN"
- The "total" should be the number of households in a province that fit each "travel time" category. In other words, the percent statistics in the table should be converted to raw numbers. Percents should be rounded with a sensible strategy. Totals after rounding should match the total in the "Number of households" column in Table 2.6. For example, if there are 100 households in Province 1 and 50.1% of the households are within less than thirty minutes from a health facility, then there should be a row that looks like this: "Province 1,LESS_THAN_THIRTY_MINUTES,50". 
- The file should be named "travel_time_to_nearest_govt_health_facility.csv"
- The file should be placed in the directory "Federal Data/Nepal Demographic and Health Survey 2016"

**Comment by hrhwilliams** [comment]
@cliftonmcintosh I'd like to work on this one too. The table also includes "Don't know" as an option. What should I do about that?

**Comment by cliftonmcintosh** [comment]
@makeroflight 

Thank you for catching that. I have updated the description to include an "UNKNOWN" value for the data. Please use that for "Don't know".

**Comment by cliftonmcintosh** [comment]
Completed with #43 

Thank you, @makeroflight
