### ISSUE TITLE
Create data set on places for washing hands

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/data#26]
For the upcoming [federal version of NepalMap](https://github.com/Code4Nepal/nepalmap_federal), we would like to present data on handwashing facilities in each household. These data are available in Table 2.8 on page 27 of the Nepal Demographic and Health Survey of 2016 ([PDF here](https://www.dhsprogram.com/pubs/pdf/FR336/FR336.pdf)). Extract the data from Table 2.7 so that it is in a csv that conforms to the following specifications:
- It should have three columns: province, handwashing place, total
- The columns should be separated by commas
- The headers should be the first row in the CSV
- The "handwashing place" options should be "FIXED", "MOBILE", "NONE"
- The "total" should be the number of households in a province that fit each "handwashing place" category. In other words, the percent statistics in the table should be converted to raw numbers. Percents should be rounded with a sensible strategy. Totals after rounding should match the total in the "Number of households" column in Table 2.8. For example, if there are 100 households in Province 1 and 50.1% of the households have a fixed place for washing hands, then there should be a row that looks like this: "Province 1,FIXED,50". 
- The file should be named "hand_washing.csv"
- The file should be placed in the directory "Federal Data/Nepal Demographic and Health Survey 2016"

**Comment by hrhwilliams** [comment]
I added the .csv for this in (#31) as well

**Comment by cliftonmcintosh** [comment]
Thank you. Small changes requested, please.
