### ISSUE TITLE
Create data set on mosquito net availability

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/data#27]
For the upcoming [federal version of NepalMap](https://github.com/Code4Nepal/nepalmap_federal), we would like to present data on possession of mosquito nets by each household. These data are available in Table 2.17 on page 39 of the Nepal Demographic and Health Survey of 2016 ([PDF here](https://www.dhsprogram.com/pubs/pdf/FR336/FR336.pdf)). Extract the data from Table 2.17 so that it is in a csv that conforms to the following specifications:
- It should have three columns: province, number of nets, total
- The columns should be separated by commas
- The headers should be the first row in the CSV
- The "number of nets" options should be "NONE", "ONE", "TWO_TO_THREE", "FOUR_OR_MORE"
- The "total" should be the number of households in a province that fit each "number of nets" category. In other words, the percent statistics in the table should be converted to raw numbers. Percents should be rounded with a sensible strategy. Totals after rounding should match the total in the "Number of households" column in Table 2.17. For example, if there are 100 total households in Province 1 and 50.1% of the households have 2-3 nets, then there should be a row that looks like this: "Province 1,TWO_TO_THREE,50". Please note that the households with no nets will need to be inferred from the percentage of households with nets.
- The file should be named "mosquito_nets.csv"
- The file should be placed in the directory "Federal Data/Nepal Demographic and Health Survey 2016"

**Comment by hrhwilliams** [comment]
I created the file and added a pull request (#30 ) to incorporate it into your data. I hope it works for you!

**Comment by cliftonmcintosh** [comment]
Thanks, it does! We appreciate your contribution, @makeroflight.

**Comment by cliftonmcintosh** [comment]
Fulfilled with #30
