### ISSUE TITLE
Create data set on food security

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/data#28]
For the upcoming [federal version of NepalMap](https://github.com/Code4Nepal/nepalmap_federal), we would like to present data on food security for each household. These data are available in Table 2.20 on page 42 of the Nepal Demographic and Health Survey of 2016 ([PDF here](https://www.dhsprogram.com/pubs/pdf/FR336/FR336.pdf)). Extract the data from Table 2.20 so that it is in a csv that conforms to the following specifications:
- It should have three columns: province, food security, total
- The columns should be separated by commas
- The headers should be the first row in the CSV
- The "food security" options should be "FOOD_SECURE", "MILDLY_FOOD_INSECURE", "MODERATELY_FOOD_INSECURE", "SEVERELY_FOOD_INSECURE"
- The "total" should be the number of households in a province that fit each "food security" category. In other words, the percent statistics in the table should be converted to raw numbers. Percents should be rounded with a sensible strategy. Totals after rounding should match the total in the "Number of households" column in Table 2.20. For example, if there are 100 total households in Province 1 and 50.1% of the households are food secure, then there should be a row that looks like this: "Province 1,FOOD_SECURE,50".
- The file should be named "food_security.csv"
- The file should be placed in the directory "Federal Data/Nepal Demographic and Health Survey 2016"

**Comment by Insiyaa** [comment]
I'd like to take this up!

**Comment by cliftonmcintosh** [comment]
@Insiyaa 

We would welcome your contribution!

**Comment by cliftonmcintosh** [comment]
Fulfilled by #45 

Thank you, @Insiyaa
