### ISSUE TITLE
Create data set on antenatal care

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/data#29]
For the upcoming [federal version of NepalMap](https://github.com/Code4Nepal/nepalmap_federal), we would like to present data on antenatal care. These data are available in Table 9.1 on page 165 of the Nepal Demographic and Health Survey of 2016 ([PDF here](https://www.dhsprogram.com/pubs/pdf/FR336/FR336.pdf)). Extract the data from Table 9.1 so that it is in a csv that conforms to the following specifications:
- It should have three columns: province, antenatal care, total
- The columns should be separated by commas
- The headers should be the first row in the CSV
- The "antenatal care" options should be "NONE", "DOCTOR", "NURSE_OR_MIDWIFE", "HEALTH_ASSISTANT", "MCH_WORKER", "COMMUNITY_HEALTH_VOLUNTEER"
- The "total" should be the number of women who had a live birth in the last five years in a province that fit each "antenatal care" category. In other words, the percent statistics in the table should be converted to raw numbers. Percents should be rounded with a sensible strategy. Totals after rounding should match the total in the "Number of women" column in Table 9.1. For example, if there are 100 total women giving birth in the last five years in Province 1 and 50.1% of the women received antenatal care from a doctor, then there should be a row that looks like this: "Province 1,DOCTOR,50".
- The file should be named "antenatal_care.csv"
- The file should be placed in the directory "Federal Data/Nepal Demographic and Health Survey 2016"

**Comment by hrhwilliams** [comment]
I created the .csv and sent a pull request to add it (#31)

**Comment by cliftonmcintosh** [comment]
The data for antenatal care looks good, @makeroflight. Thank you!
