### ISSUE TITLE
Create data set on oral polio vaccination rates in children ages 12-23 months

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/data#32]
For the upcoming [federal version of NepalMap](https://github.com/Code4Nepal/nepalmap_federal), we would like to present data on oral polio vaccination rates. These data are available in Table 10.3 on page 212 of the Nepal Demographic and Health Survey of 2016 ([PDF here](https://www.dhsprogram.com/pubs/pdf/FR336/FR336.pdf)). Extract the data from Table 10.3 so that it is in a csv that conforms to the following specifications:
- It should have three columns: province, number of doses, total
- The columns should be separated by commas
- The headers should be the first row in the CSV
- The "number of doses" options should be "NONE", "ONE", "TWO", "THREE"
- The "total" should be the number of children age 12-23 months in a province whose parents were surveyed and whose dosage under the "Polio" header in the table fits each "number of doses" category. In other words, the percent statistics in the table should be converted to raw numbers. Percents should be rounded with a sensible strategy. Totals after rounding should match the total in the _first_ "Number of children" column in Table 10.3. 
- **Note that the values are cumulative.** For example, if 1 dose is at 75%, 2 doses is at 65%, and 3 doses is at 40%, that means that 10% of the children have received only one dose, 25% of the children have received only 2 doses, 40% have received 3 doses and 25% have received no doses.
- Calculate raw numbers from the percentages. For example, if there are 100 total children age 12-23 months in Province 1 and 50.1% of the children have received one dose of oral polio vaccine, then there should be a row that looks like this: "Province 1,ONE,50". Please note that the number of children who have received no oral polio vaccine doses will need to be inferred from the percentage of children who have received one or more. **Please note that there are TWO "number of children" columns. You should use the first "number of children" column (16th column overall) because it is the one that is for children ages 12-23 months. The last column in the table is NOT the one to use because it is for older children.**
- The file should be named "oral_polio_vaccination_twelve_to_twenty_three_months.csv"
- The file should be placed in the directory "Federal Data/Nepal Demographic and Health Survey 2016"

**Comment by msdeibel** [comment]
I'll take this one.

**Comment by cliftonmcintosh** [comment]
Completed in #46 

@msdeibel  thank you
