### ISSUE TITLE
Create data set on overall vaccination rates for children ages 12-23 months

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/data#37]
For the upcoming [federal version of NepalMap](https://github.com/Code4Nepal/nepalmap_federal), we would like to present data on overall vaccination rates for children ages 12-23 months. These data are available in Table 10.3 on page 212 of the Nepal Demographic and Health Survey of 2016 ([PDF here](https://www.dhsprogram.com/pubs/pdf/FR336/FR336.pdf)). Extract the data from Table 10.3 so that it is in a csv that conforms to the following specifications:
- It should have three columns: province, vaccinations, total
- The columns should be separated by commas
- The headers should be the first row in the CSV
- The "vaccinations" options should be "NONE", "SOME", "BASIC", "ALL"
-- "NONE" is for the column "No vaccinations" in Table 10.3
-- "BASIC" is for the column  "All basic vaccinations" in Table 10.3
-- "ALL" is for the column "All age-appropriate vaccinations" in Table 10.3
-- "SOME" is for 100% minus the percent who have received basic vaccinations minus the percent who have received no vaccinations.
- Note that the values are cumulative. Here is an example using Province 1 data: 

| All basic vaccinations | All age-appropriate vaccinations | No vaccinations | Number of children |
|------------------------------|---------------------------------------------|-----------------------|--------------------------|
| 79.4 | 43.1 | 0.8 | 169 |

Since 0.8% have received none, the value for "NONE" is 169 * 0.008.
Since 43.1% have received "All age-appropriate vaccinations", the value for "ALL" is 169 * 0.431
The percent receiving "BASIC" is calculated by subtracting the percentage receiving "All age-appropriate vaccinations" from the percentage receiving "All basic vaccinations". So 169 * (0.794 - 0.431)
The percent receiving "SOME" is calculated by subtracting the percentage receiving none and the percentage receiving all basic from 100%. So 169 * (1 - 0.794 - 0.008).

- The "total" should be the number of children age 12-23 months in a province who fit in one of the four groups described above. In other words, the percent statistics in the table should be converted to raw numbers. Percents should be rounded with a sensible strategy. Totals after rounding should match the total in the _first_ "Number of children" column in Table 10.3. **Please note that the last two columns in the table are not for children ages 12-23 months. The columns to be used for this data set are in columns 13-16 in the table.** For example, if there are 100 total children age 12-23 months in Province 1 and 50.1% of the children are in the "All basic vaccinations" column, then there should be a row that looks like this: "Province 1,BASIC,50".
- The file should be named "overall_vaccination_twelve_to_twenty_three_months.csv"
- The file should be placed in the directory "Federal Data/Nepal Demographic and Health Survey 2016"

**Comment by rafagarciac** [comment]
@cliftonmcintosh  I'll do it let me 1h more or less ! 😁

**Comment by rafagarciac** [comment]
### Done in the #39 PR. 
We have to help to the most neddy of many ways!
This it's one of them - RG

**Comment by cliftonmcintosh** [comment]
@ravinepal 

Any idea why the percentages for overall vaccination rates don't add up in table 10.3?

For example, Province 1 has the following:

| Basic Vaccination | All Age-appropriate vaccinations | No vaccinations |
|-------------------------|---------------------------------------------|-----------------------|
| 79.4% | 43.1% | 0.8% |

Are those categories mutually exclusive and should add up to 100%? If not, are the first two cumulative? If so, then I would expect "No vaccinations" to be larger. Or is there a fourth category of "some vaccines but not enough to be "all basic"? I'm not sure how we interpret those numbers. Can you provide guidance? I've attached the relevant table in this comment.

[Nepal Demographic and Health Survey 2016 [FR336] Table 10.3.pdf](https://github.com/Code4Nepal/data/files/2454419/Nepal.Demographic.and.Health.Survey.2016.FR336.Table.10.3.pdf)

**Comment by cliftonmcintosh** [comment]
@rafagarciac 

It looks like there may be discrepancies in the data. Please hold off on this until we get guidance. Please consider doing another one of the issues instead.

**Comment by cliftonmcintosh** [comment]
Re-opened issue. Provided more guidance in description.

**Comment by rafagarciac** [comment]
@cliftonmcintosh Yes I'll do but first I need that you explain better this parts of the description:
- Note that the values are cumulative. For example, if 1 dose is at 75%, 2 doses is at 65%, and 3 doses is at 40%, that means that 10% of the children have received only one dose, 25% of the children have received only 2 doses, 40% have received 3 doses and 25% have received no doses.
- My interpretation: (75% + 65% + 40%) -> 100% |||   (180% * 1 dose 75%) / 100% -> Result.

**Comment by cliftonmcintosh** [comment]
@rafagarciac 

Thank you for your response. I think the data are slightly different from your interpretation. I have updated the description using Province 1 as an example. Please let me know if that helps explain the data and our goal.

**Comment by cliftonmcintosh** [comment]
@ravinepal 

Can you verify whether or not my interpretation of how to read the percentages is correct? Please see my interpretation in the description.

**Comment by rafagarciac** [comment]
@cliftonmcintosh Update the  in the overall_vaccination_twelve_to_twenty_three_months.csv file #37 in the commit: 5ff39f7fcf7210293031b6802a0e13765b6fa471
Example:
province, vaccinations, total
- Province 1, NONE, 1
- Province 1, BASIC, 73
- Province 1, ALL, 61
- Province 1, SOME, 34
- Province 2, NONE, 5

> Total of children = 169

**Comment by cliftonmcintosh** [comment]
Fulfilled by #39 

Thank you, @rafagarciac
